### PR TITLE
Updated gson to remove vulnerability

### PR DESCRIPTION
**Pull request by Furlanetto-Dev**

### CODE REVIEW

**Review by timguy — APPROVED** [review]

**Comment by timguy** [comment]
would need this as well but I am also not a "reviewer with write access"

**Comment by Furlanetto-Dev** [comment]
> would need this as well but I am also not a "reviewer with write access"

yeah me too, I just don't remember why I needed this 5 months ago, I remember that I had to fork this and manually change the version.

It's kinda of sad seeing this useful repo getting abandoned, maybe I just don't know anything better, or I'm programming wrong (I know that using reflections in java can be super sketchy)

**Comment by Furlanetto-Dev** [comment]
such a simple edit....

**Comment by timguy** [comment]
just publish your fork and have an eye on the PRs ;-).

**Pull request closed without merging**
