### PR TITLE
Shaleen 338

### PR DESCRIPTION
**Pull request by ShaleenMehrotra**
Reduced code smells for org.reflections.vfs

### CODE REVIEW

**Comment by ShaleenMehrotra** [comment]
Please approve the merge request @ronmamo

**Comment by ronmamo** [comment]
thanks @ShaleenMehrotra 
interested to hear your thoughts on #338 , the vfs package needs a general remake...

**Comment by ShaleenMehrotra** [comment]
@ronmamo I am unable to figure out why the compilation failed. The build passes locally and all the tests pass too. I have renamed the variables that the build is looking for.

**Comment by ronmamo** [comment]
sorry @ShaleenMehrotra , even though code cleanup is a good idea, the vfs module needs a rewrite #338

**Pull request closed without merging**
