### PR TITLE
PR to address #98 and rework withParametersAssignable

### PR DESCRIPTION
**Pull request by jamieps**
Split `withParametersAssignable` into 
- `withParameterAndSubclasses` which finds methods with parameters matching a class and any of its subclasses (this replicates pre-v0.9.9 behaviour) 
- `withParameterAndSuperclasses` which locates superclasses (this replicates the post-v0.9.9 behaviour).

### CODE REVIEW

**Comment by ronmamo** [comment]
good idea, but the naming is not clear enough.

**Comment by jamieps** [comment]
Do you have any suggestions on what they should be renamed to?

**Comment by jamieps** [comment]
@ronmano any suggestions on method names for this?

**Comment by fibbers** [comment]
I'm using 0.9.10 and also expected different behaviour:

```java
Set<Constructor> constructorsAcceptingFruitTypes = getAllConstructors(
    classes,
    withParametersAssignableTo(Fruit.class));
// constructors accepting Fruit, Orange, Apple, Pear
```

how about adding `withParametersAssignableFrom`, e.g.:
```java
Set<Constructor> constructorsAcceptingAnApple = getAllConstructors(
    classes,
    withParametersAssignableFrom(Apple.class));
// constructors accepting Apple, Fruit, Object
```
Now that I read back issue #23, I see this idea is exactly mentioned in https://github.com/ronmamo/reflections/issues/23#issuecomment-99437249:
- `Apple` is assignable **to** `Fruit`: `Fruit fruit = (Apple) apple;`
- `Fruit` is assignable **from** `Apple`: some use-case as above, but mentioned differently

PS: I am aware this PR is almost a year old, but nevertheless wanted to suggest this

**Comment by ronmamo** [comment]
@jamieps @fibbers sorry I was too lazy, and it seems outdated now... please resubmit if interested 🥇

**Comment by evanw555** [comment]
@ronmamo I'm sorry but the PR that addresses this has the to/from logic backwards... @fibbers is totally right in his assessment of what "to" means and what "from" means. If there is not a PR open already to reverse this, I may open one myself.

**Pull request closed without merging**
