### PR TITLE
Add LICENSE file for BSD

### PR DESCRIPTION
**Pull request by kcooney**
BSD is listed in the `<licenses>` section of pom.xml, but there is no license file. I'm hoping there's no concerns with adding a license file (and updating the related section of README.md). Thanks!

### CODE REVIEW

**Comment by kcooney** [comment]
Ron, any change this pull request could be merged?

Thanks!

**Comment by kcooney** [comment]
@ronmamo any chance this pull request could be merged?

Thanks!

**Comment by ronmamo** [comment]
License is WTFPL.
I would even use a shorter version of it (if there was).
This library is published as an act of giving and generosity, from developers to developers. All the licensing governance mumble jumble does not concern me.
Please feel free to use it, and to contribute to the developers community in the same manner. One solution is to fork it and use another license.

**Comment by kcooney** [comment]
@ronmamo I ask you respectfully to please reconsider. Although you might think that using the WTFPL license allows anyone to use your software, it doesn't.. But by simply pressing one button to merge this PR organizations that require a real license can use your software.

Having one more file in your repository does no harm to you or the maintenance of your project, but does immeasurable help.to other deveopers. It would be a huge "act of giving and generosity" to potentially thousands of developers to give this useful project a real license .

One last food for thought: My company does not allow me to send bug fixes to you due to the current license,, and many other companies have the same policy. I personally think it's a ridiculous restriction, but my hands are tied.

**Pull request closed without merging**
